import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar/Navbar";
import FreeShipping from './../components/FreeShipping/FreeShipping';
import Footer from "@/components/Footer/Footer";
import FooterFreeShipping from '../components/FooterFreeShipping/FooterFeaturesBar';
import { Toaster } from "@/components/ui/sonner";
import MySession from './../components/MySession/MySession';

const inter = Exo({ subsets: ['latin'], variable: '--font-exo' });

export const metadata: Metadata = {
  title: "FreshCart",
  description: "Generated by Omar Elhalawany",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", inter.variable)}>
      <body
        className={`antialiased`}>
        <MySession>
          <FreeShipping />
          <Navbar />
          <Toaster />
          {children}
          <FooterFreeShipping />
          <Footer />
        </MySession>
      </body>
    </html>
  );
}
